version = 0.1

[default.deploy]
[default.deploy.parameters]
template_file = "template.yaml"
stack_name = "profile-site-pipeline"
region = "ap-northeast-1"
s3_prefix = "profile-site-pipeline"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "GitHubConnectionName=gh-profile-site",
    "GitHubFullRepositoryId=Go-Morishita/profile-site",
    "ClientBucketName=profile-site-s3-bucket",
    "CloudFrontDistributionId=EDI731TZGURZO",
    "MicroCMSServiceDomain=gomorishita-blog",
    "MicroCMSApiKey=nXeGjxQ2fXQenCayVYxH10n7PG6ipEoojfqK",
    ]
fail_on_empty_changeset = false
resolve_s3 = true